os: linux
language: python
cache: pip
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
jobs:
  allow_failures:
    - env: TOX_ENV=py36-djmaster-sqlite
    - env: TOX_ENV=py36-djmaster-postgres
    - env: TOX_ENV=py37-djmaster-sqlite
    - env: TOX_ENV=py37-djmaster-postgres
    - env: TOX_ENV=py38-djmaster-sqlite
    - env: TOX_ENV=py38-djmaster-postgres
install:
  - pip install tox-travis
services:
  - postgresql
before_script:
  - psql -c 'create database extra_settings;' -U postgres
script:
  - tox